### ISSUE TITLE
incorrect image link

### ISSUE THREAD

**Issue by mafranks** [mwrouse/Python_DuckHunt#2]
When I tried to run this, I got an error.

`
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/livewires/games.py", line 842, in load_image
    surface = pygame.image.load(filename)
FileNotFoundError: No file 'sprites\spawner.png' found in working directory '/Users/mafranks/PycharmProjects/DuckHunt-Python'.
`

If I change line 402 of DuckHunt.py from

`
    image = games.load_image("sprites\spawner.png")
`

to
 
`
    image = games.load_image("Sprites/spawner.png")
`

then it works.

**Comment by mwrouse** [comment]
Okay, thanks. We changed it. First commit in 7 years lol
